import uuid

out_file = 'd:/code/Flutter_Android/Flutter_Android/AI_LMS_PRD/seed_data/10_insert_submission_answers.sql'

with open(out_file, 'w', encoding='utf-8') as f:
    f.write('BEGIN;\n')
    f.write('-- Generate submission answers for all seeded submissions\n\n')

    f.write("""
DO $$
DECLARE
    sub RECORD;
    aq RECORD;
    sa_id uuid;
    pts numeric;
    base_uuid varchar := 'ffaa0000-0000-4a00-c000-';
    cnt integer := 1;
BEGIN
    FOR sub IN 
        SELECT s.id as submission_id, s.session_id, s.assignment_id, s.student_id 
        FROM submissions s 
        WHERE s.id::text LIKE 'ff00%' AND s.session_id IS NOT NULL
    LOOP
        FOR aq IN 
            SELECT id, points FROM assignment_questions 
            WHERE assignment_id = sub.assignment_id
        LOOP
            -- Generate deterministic UUID for submission_answer
            sa_id := CAST(base_uuid || LPAD(cnt::text, 12, '0') AS uuid);
            pts := aq.points;
            IF pts IS NULL THEN
                pts := 1.0;
            END IF;
            
            INSERT INTO submission_answers (
                id, session_id, assignment_question_id, answer, 
                final_score, ai_score, created_at, updated_at, graded_by, graded_at
            ) VALUES (
                sa_id, sub.session_id, aq.id, '{"selected_choice_ids": [0]}'::jsonb, 
                pts, pts, NOW(), NOW(), '51e467a2-9033-5e85-b666-164ea075f6c9', NOW()
            ) ON CONFLICT DO NOTHING;
            
             -- Auto insert into ai_queue so teacher screen shows AI graded successfully?
             -- Actually, no need to insert to ai_queue if we provide 'final_score' and 'ai_score',
             -- but for UI components that check `ai_queue`, it might read from `submission_answers` or `submissions.ai_graded` instead.
             -- The submissions generated by seed_data/08_analytics_diversity_seed.sql already have ai_graded = TRUE.
            
            cnt := cnt + 1;
        END LOOP;
    END LOOP;
END $$;
""")
    f.write('\nCOMMIT;\n')
print("10_insert_submission_answers.sql generated successfully.")
