import 'package:ai_mls/domain/entities/recommendation/recommendation.dart';

/// Repository interface for recommendation operations.
///
/// NOTE: The ai_recommendations table does NOT support client-side creation
/// (recommendations are generated by backend/AI rules).
/// The table has no `is_read` column — only `dismissed` for visibility control.
abstract class RecommendationRepository {
  /// Get recommendations for a user (teacher or student)
  Future<List<Recommendation>> getRecommendations({
    required String userId,
    required String role,
    String? classId,
    int limit = 20,
  });

  /// Dismiss a recommendation (sets dismissed=true)
  Future<bool> dismissRecommendation(String recommendationId);

  /// Bulk dismiss multiple recommendations
  Future<bool> bulkDismiss(List<String> ids);

  /// Get peer comparison data for a student in a class
  Future<PeerComparison> getPeerComparison(String studentId, String classId);
}
