import 'package:envied/envied.dart';

part 'env.g.dart';

/// Environment configuration class generated by envied
///
/// This class provides compile-time type-safe access to environment variables.
/// The actual values are loaded from .env files at build time.
///
/// Usage:
/// - Development: Use .env.dev file
/// - Staging: Use .env.staging file
/// - Production: Use .env.prod file
///
/// To generate the env.g.dart file, run:
/// ```bash
/// flutter pub run build_runner build --delete-conflicting-outputs
/// ```
///
/// For different environments, use:
/// ```bash
/// # Development
/// flutter run --dart-define=ENV_FILE=.env.dev
///
/// # Staging
/// flutter run --dart-define=ENV_FILE=.env.staging
///
/// # Production
/// flutter run --dart-define=ENV_FILE=.env.prod
/// ```

@Envied(
  path: String.fromEnvironment('ENV_FILE', defaultValue: '.env.dev'),
  name: 'Env',
)
abstract class Env {
  /// Supabase project URL
  @EnviedField(varName: 'SUPABASE_URL')
  static final String supabaseUrl = _Env.supabaseUrl;

  /// Supabase anonymous key (public, safe for client-side use)
  @EnviedField(
    varName: 'SUPABASE_ANON_KEY',
    obfuscate: true, // Obfuscate in compiled binary
  )
  static final String supabaseAnonKey = _Env.supabaseAnonKey;

  /// Supabase service role key (secret, should only be used server-side)
  /// Note: This should NOT be used in client-side code for security reasons.
  /// Only included here for completeness - use server-side only.
  @EnviedField(varName: 'SUPABASE_SERVICE_ROLE_KEY', obfuscate: true)
  static final String supabaseServiceRoleKey = _Env.supabaseServiceRoleKey;
}
