import 'package:envied/envied.dart';

part 'env.g.dart';

/// Environment configuration class generated by envied
///
/// This class provides compile-time type-safe access to environment variables.
/// The actual values are loaded from .env files at build time.
///
/// Usage:
/// - Development: Use .env.dev file
/// - Staging: Use .env.staging file
/// - Production: Use .env.prod file
///
/// To generate the env.g.dart file, run:
/// ```bash
/// flutter pub run build_runner build --delete-conflicting-outputs
/// ```
///
/// For different environments, use:
/// ```bash
/// # Development
/// flutter run --dart-define=ENV_FILE=.env.dev
///
/// # Staging
/// flutter run --dart-define=ENV_FILE=.env.staging
///
/// # Production
/// flutter run --dart-define=ENV_FILE=.env.prod
/// ```

@Envied(
  path: String.fromEnvironment('ENV_FILE', defaultValue: '.env.dev'),
  name: 'Env',
)
abstract class Env {
  /// Supabase project URL
  @EnviedField(varName: 'SUPABASE_URL')
  static final String supabaseUrl = _Env.supabaseUrl;

  /// Supabase anonymous key (public, safe for client-side use)
  @EnviedField(
    varName: 'SUPABASE_ANON_KEY',
    obfuscate: true, // Obfuscate in compiled binary
  )
  static final String supabaseAnonKey = _Env.supabaseAnonKey;

  /// Sentry DSN for error reporting
  /// Get your DSN from https://sentry.io/settings/YOUR_ORG/projects/YOUR_PROJECT/keys/
  /// Nếu chưa cấu hình (dev/local), để trống vẫn cho phép build_runner generate.
  @EnviedField(varName: 'SENTRY_DSN', obfuscate: true, defaultValue: '')
  static final String sentryDsn = _Env.sentryDsn;

  /// AI API base URL for question generation
  /// Example: https://api.example.com/v1
  @EnviedField(varName: 'AI_API_BASE_URL', defaultValue: '')
  static final String aiApiBaseUrl = _Env.aiApiBaseUrl;

  /// AI API key for authentication
  /// Obfuscate để bảo mật API key
  @EnviedField(varName: 'AI_API_KEY', obfuscate: true, defaultValue: '')
  static final String aiApiKey = _Env.aiApiKey;

  /// Gemini API key for Google Gemini API
  /// Obfuscate để bảo mật API key
  @EnviedField(varName: 'GEMINI_API_KEY', obfuscate: true, defaultValue: '')
  static final String geminiApiKey = _Env.geminiApiKey;
}
